[package]
name = "python"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
pyo3.workspace = true
itertools.workspace = true
log.workspace = true
tokio.workspace = true
tracing.workspace = true
util.workspace = true
