[package]
name = "python"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
lib.workspace = true
pyo3.workspace = true
itertools.workspace = true
log.workspace = true
tokio.workspace = true
tracing.workspace = true
