version: '3'
services:
  app:
    container_name: riamu.v3
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=sqlite://data/db.sqlite?mode=rwc
      - CACHE_WORKING_DIR=/app/cache
      - CACHE_BASE_URL=https://riamu.desu.dedyn.io/
      - CACHE_LIMIT_GiB=10
    volumes:
      - data:/app/data
      - ./python:/app/python
      - ./assets:/app/assets
      - ~/dev/services/data/www/riamu:/app/cache
    restart: unless-stopped
    init: true
  nginx:
    container_name: riamu.v3-nginx
    image: nginx
    entrypoint: []
    network_mode: host
    volumes:
      - ./nginx/config-embed-hack:/etc/nginx:ro
      - ./.cache:/usr/share/riamu/cache:ro
    restart: unless-stopped
    init: true
volumes:
  data:
