[package]
name = "c"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
cairo-rs.workspace = true

[build-dependencies]
bindgen.workspace = true
pkg-config.workspace = true
