#!/usr/bin/env bash
set -euo pipefail

# https://stackoverflow.com/a/73254328/8802501
# https://stackoverflow.com/a/75966904/8802501

mkdir -p .tmp
trap 'rm -rf .tmp' EXIT

# ---

git clone -n --depth=1 --filter=tree:0 https://github.com/basmilius/weather-icons.git .tmp/weather-icons
cd .tmp/weather-icons
  git sparse-checkout set --sparse-index production/fill/svg-static
  git checkout
cd -

mkdir -p assets/icons/weather
find .tmp -name '*.svg' -type f -exec mv -t assets/icons/weather {} +
rm -rf .tmp/*

# ---

git clone -n --depth=1 --filter=tree:0 https://github.com/google/material-design-icons.git .tmp/material-icons
cd .tmp/material-icons
  git sparse-checkout set --no-cone 'variablefont/MaterialSymbolsOutlined\[*\].ttf'
  git checkout
cd -

git clone -n --depth=1 --filter=tree:0 https://github.com/googlefonts/roboto-flex.git .tmp/roboto-flex
cd .tmp/roboto-flex
  git sparse-checkout set --no-cone 'fonts/RobotoFlex\[*\].ttf'
  git checkout
cd -

git clone -n --depth=1 --filter=tree:0 https://github.com/google/fonts.git .tmp/google-fonts
cd .tmp/google-fonts
  git sparse-checkout set --no-cone 'ofl/notosans*/NotoSans*\[*\].ttf' \
    '!*Italic*' '!*Mono*' '!*Display*' '!*Looped*' '!*Unjoined*'
  git checkout
cd -

# git clone -n --depth=1 --filter=tree:0 https://github.com/notofonts/notofonts.github.io.git .tmp/noto
#   cd .tmp/noto
#   git sparse-checkout set --no-cone 'fonts/*/googlefonts/variable/NotoSans*\[*\].ttf' \
#     '!*Italic*' '!*Mono*'
#   git checkout
# cd -

# git clone -n --depth=1 --filter=tree:0 https://github.com/notofonts/noto-cjk.git .tmp/noto-cjk
# cd .tmp/noto-cjk
#   git sparse-checkout set --no-cone 'google-fonts/NotoSans*\[*\].ttf'
#   git checkout
# cd -

mkdir -p assets/fonts
find .tmp -name '*.ttf' -type f -exec mv -t assets/fonts {} +
rm -rf .tmp/*
